// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// SimCensorX
SEXP SimCensorX(Rcpp::DataFrame data1, Rcpp::NumericVector maxtime1, Rcpp::CharacterVector form1, Rcpp::DataFrame D1, int maxiter);
RcppExport SEXP missDeaths_SimCensorX(SEXP data1SEXP, SEXP maxtime1SEXP, SEXP form1SEXP, SEXP D1SEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type data1(data1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type maxtime1(maxtime1SEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type form1(form1SEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type D1(D1SEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(SimCensorX(data1, maxtime1, form1, D1, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// SurvExpPrep
SEXP SurvExpPrep(Rcpp::DataFrame D1, double time);
RcppExport SEXP missDeaths_SurvExpPrep(SEXP D1SEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type D1(D1SEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(SurvExpPrep(D1, time));
    return rcpp_result_gen;
END_RCPP
}
// SurvExpInit
void SurvExpInit(SEXP poptable);
RcppExport SEXP missDeaths_SurvExpInit(SEXP poptableSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type poptable(poptableSEXP);
    SurvExpInit(poptable);
    return R_NilValue;
END_RCPP
}
// SurvTime
double SurvTime(double birthyear, double age, double probability, int sex);
RcppExport SEXP missDeaths_SurvTime(SEXP birthyearSEXP, SEXP ageSEXP, SEXP probabilitySEXP, SEXP sexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type birthyear(birthyearSEXP);
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type probability(probabilitySEXP);
    Rcpp::traits::input_parameter< int >::type sex(sexSEXP);
    rcpp_result_gen = Rcpp::wrap(SurvTime(birthyear, age, probability, sex));
    return rcpp_result_gen;
END_RCPP
}
// SurvProbability
double SurvProbability(double birthyear, double age, double time, int sex);
RcppExport SEXP missDeaths_SurvProbability(SEXP birthyearSEXP, SEXP ageSEXP, SEXP timeSEXP, SEXP sexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type birthyear(birthyearSEXP);
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< int >::type sex(sexSEXP);
    rcpp_result_gen = Rcpp::wrap(SurvProbability(birthyear, age, time, sex));
    return rcpp_result_gen;
END_RCPP
}
// SurvDump
SEXP SurvDump(int year, int sex);
RcppExport SEXP missDeaths_SurvDump(SEXP yearSEXP, SEXP sexSEXP) {
    BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type year(yearSEXP);
    Rcpp::traits::input_parameter< int >::type sex(sexSEXP);
    rcpp_result_gen = Rcpp::wrap(SurvDump(year, sex));
    return rcpp_result_gen;
    END_RCPP
}
