# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SimCensorX <- function(data1, maxtime1, form1, D1, maxiter) {
    .Call('missDeaths_SimCensorX', PACKAGE = 'missDeaths', data1, maxtime1, form1, D1, maxiter)
}

SurvExpPrep <- function(D1, time) {
    .Call('missDeaths_SurvExpPrep', PACKAGE = 'missDeaths', D1, time)
}

SurvExpInit <- function(poptable) {
    invisible(.Call('missDeaths_SurvExpInit', PACKAGE = 'missDeaths', poptable))
}

SurvTime <- function(birthyear, age, probability, sex) {
    .Call('missDeaths_SurvTime', PACKAGE = 'missDeaths', birthyear, age, probability, sex)
}

SurvProbability <- function(birthyear, age, time, sex) {
    .Call('missDeaths_SurvProbability', PACKAGE = 'missDeaths', birthyear, age, time, sex)
}

SurvDump <- function(year, sex) {
    .Call('missDeaths_SurvDump', PACKAGE = 'missDeaths', year, sex)
}

